micronaut:
  application:
    name: payment-charging-service
temporal:
  target: ${TEMPORAL_TARGET:localhost:7233}
  namespace: ${TEMPORAL_NAMESPACE:default}
  task-queue: payment-charging-activities
